server.port=${SERVER_PORT:8082}

spring.application.name=webflux-r2dbc

spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/orders_db}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:postgres}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:postgres}
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.initial-size=10

mock.service.base-url=${MOCK_SERVICE_BASE_URL:http://localhost:9090}

spring.sql.init.mode=never

management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.show-details=always

logging.level.root=WARN
logging.level.com.cloudwebframeworks=INFO